---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-vm-1
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubevirt-vm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubevirt-vm
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: test-vm-1
  targetNamespace: virtualmachines
  values:
    vm:
      cloudInit:
        userData: |
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
      containerDisk:
        image: quay.io/containerdisks/fedora:latest
      hostname: test-vm-1
      memory: 1024Mi
