apiVersion: v1
kind: Pod
metadata:
  name: vm-provisioner
spec:
  serviceAccountName: vm-prov-sa
  containers:
  - name: vm-provisioner
    image: ttl.sh/vm-provisioner:v0.0.1
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
